modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
description='''一个星露谷物语风格的HUD模组，可显示时间、天气、运势和物品计数器'''
authors="Weatheraintbad"
logoFile="assets/${mod_id}/icon.png"

[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
versionRange="${neo_version}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"